name = "Abyss"
os = "Windows"
type = "Standalone"
status = "Active"
access = "Paid"
website = "https://discord.gg/PsxTepWNYg"

[features]
movement = true
esp = true
teleports = true
vr = true
crashers = true
protections = true
