name = "Emperium"
os = "Linux"
type = "BepInEx"
status = "Inactive"
access = "Free"
website = "https://discord.gg/myuWgYP8WS"

[features]
movement = true
esp = true
teleports = true
vr = true
crashers = false
protections = false
