name = "Exo"
os = "Windows"
type = "Standalone"
status = "Inactive"
access = "Paid"
website = "https://discord.gg/yMHTVPXRAq"

[features]
movement = true
esp = true
teleports = true
vr = true
crashers = false
protections = true
