name = "Hexedware"
os = "Windows"
type = "Standalone"
status = "Active"
access = "Paid"
website = "https://hexed.cc"

[features]
movement = true
esp = true
teleports = true
vr = true
crashers = true
protections = true
