name = "Hollow"
os = "Windows"
type = "Standalone"
status = "Active"
access = "Paid"
website = "https://hollow.enterprises"

[features]
movement = true
esp = true
teleports = true
vr = false
crashers = false
protections = true
