name = "MekaMod"
os = "Windows & Linux"
type = "MelonLoader"
status = "Active"
access = "Invite"
website = "https://discord.gg/Qtt4G8cURs"

[features]
movement = true
esp = true
teleports = true
vr = true
crashers = false
protections = false
