name = "Serenade"
os = "Windows & Linux"
type = "Abyss Loader"
status = "Active"
access = "Paid"
website = "https://vrc.serenade.rip"

[features]
movement = true
esp = true
teleports = true
vr = true
crashers = true
protections = true
