name = "Skill Issue"
os = "Windows"
type = "BepInEx"
status = "Active"
access = "Paid"
website = "https://skillissue.one/"

[features]
movement = true
esp = true
teleports = true
vr = true
crashers = false
protections = true
